---
- name: Deploy from Docker Hub
  hosts: all
  become: yes
  tasks:
    - name: Install Docker and Docker-Compose
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - docker.io
        - docker-compose

    - name: Create app directory
      file:
        path: /home/vagrant/app
        state: directory

    - name: Copy docker-compose file only
      copy:
        src: "/vagrant/docker-compose.yml"
        dest: "/home/vagrant/app/docker-compose.yml"
        remote_src: yes

    - name: Pull latest images from Docker Hub
      shell:
        cmd: docker-compose pull
        chdir: /home/vagrant/app

    - name: Start Application
      shell:
        cmd: docker-compose up -d
        chdir: /home/vagrant/app